package com.spendly.app.core.ui.theme

import androidx.compose.ui.graphics.Color

// Light palette
val LightPrimary = Color(0xFF16A34A)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFDCFCE7)
val LightOnPrimaryContainer = Color(0xFF052E16)
val LightSecondary = Color(0xFFF59E0B)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFEF3C7)
val LightOnSecondaryContainer = Color(0xFF451A03)
val LightBackground = Color(0xFFF7F8FA)
val LightOnBackground = Color(0xFF111827)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF111827)
val LightSurfaceVariant = Color(0xFFEEF1F4)
val LightOnSurfaceVariant = Color(0xFF6B7280)
val LightOutline = Color(0xFFE2E5E9)
val LightError = Color(0xFFDC2626)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFEE2E2)
val LightOnErrorContainer = Color(0xFF450A0A)

// Dark palette
val DarkPrimary = Color(0xFF22C55E)
val DarkOnPrimary = Color(0xFF00390F)
val DarkPrimaryContainer = Color(0xFF0A5C28)
val DarkOnPrimaryContainer = Color(0xFFBBF7D0)
val DarkSecondary = Color(0xFFFBBF24)
val DarkOnSecondary = Color(0xFF452B00)
val DarkSecondaryContainer = Color(0xFF6B4A00)
val DarkOnSecondaryContainer = Color(0xFFFEF3C7)
val DarkBackground = Color(0xFF0F1115)
val DarkOnBackground = Color(0xFFF3F4F6)
val DarkSurface = Color(0xFF171A21)
val DarkOnSurface = Color(0xFFF3F4F6)
val DarkSurfaceVariant = Color(0xFF23272F)
val DarkOnSurfaceVariant = Color(0xFF9CA3AF)
val DarkOutline = Color(0xFF3A3F4A)
val DarkError = Color(0xFFF87171)
val DarkOnError = Color(0xFF4C0000)
val DarkErrorContainer = Color(0xFF7F1D1D)
val DarkOnErrorContainer = Color(0xFFFEE2E2)
